# Generated by Django 3.2.5 on 2024-01-23 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_leader',
        ),
    ]
